### ISSUE TITLE
[BUG] The 'table-striped' can appear abnormal in late night mode

### ISSUE THREAD

**Issue by haitanghuadeng** [tabler/tabler#1313] opened 2022-10-11 02:19 UTC
You can click the [link](https://preview.tabler.io/tables.html?theme=dark) to add 'table-striped' to the table style, then toggle the late-night theme, and the question reappears.

**Comment by dekoza** [comment] 2022-10-16 22:49
Duplicate of #1308 ?

**Comment by codecalm** [comment] 2022-10-17 09:45
Duplicate of https://github.com/tabler/tabler/issues/1308

**Closed by codecalm** 2022-10-17 09:45 UTC
Labels: bug
