### ISSUE TITLE
Feature needed: Sidebar

### ISSUE THREAD

**Issue by iamkallolpratim** [tabler/tabler#86] opened 2018-04-13 11:52 UTC
Hi @codecalm  ,  Can you add a sidebar on this template

**Comment by johnunclesam** [comment] 2018-04-13 12:10
Please, PR.

**Comment by beeman** [comment] 2018-04-13 19:30
Duplicate of #83

**Closed by beeman** 2018-04-13 19:30 UTC

**Comment by neerajsinghsonu** [comment] 2019-09-14 10:55
Hi, You can find a [demo here](https://github.com/tabler/tabler/issues/83#issuecomment-531470052)

Thank you :)
