### ISSUE TITLE
[FEATURE] New layout based on collapsed captions - only icons

### ISSUE THREAD

**Issue by rogersantosferreira** [tabler/tabler#1869] opened 2024-04-14 23:59 UTC
**Is your feature request related to a problem? Please describe.**
There is no problem at all. Just the need for collapsed menu that only shows de icons when it is at left or tight from the page.

**Describe the solution you'd like**
When the user put the mouse inside the menu, it just expands it self to the normal width.

**Describe alternatives you've considered**
It's not applicable.

Here is one example:
![image](https://github.com/tabler/tabler/assets/3109538/44ab0fcd-15e9-4bff-a951-01a7a3b13538)

Thanks in advance. Maybe it will increase the flexibility of this awesome work.
Sorry about my english. It's not my first language.

**Comment by kevinpapst** [comment] 2024-05-18 07:25
Duplicate of https://github.com/tabler/tabler/issues/1803 - all of you who voted here, please vote in the original post

**Closed by kevinpapst** 2024-05-18 07:25 UTC
Labels: duplicate
