### ISSUE TITLE
[FEATURE] I hope tabs support scrolling when there are too many tabs

### ISSUE THREAD

**Issue by qwer130140190** [tabler/tabler#1369] opened 2022-11-13 04:48 UTC
Especially for horizontal tabs, the inability to scroll will result in the inability to deform in small mobile devices.
Or add left and right buttons on both sides

**Comment by abalter** [comment] 2022-12-03 20:39
I also want this.

**Comment by kevinpapst** [comment] 2023-02-22 17:21
Bootstrap itself doesn't have tab scrolling: https://getbootstrap.com/docs/5.2/components/navs-tabs/

Do you know of any library that could support this feature?

**Comment by kevinpapst** [comment] 2023-02-22 17:23
Now I see that the issue was already posted. Closing as duplicate of #1316

**Closed by kevinpapst** 2023-02-22 17:23 UTC
Labels: duplicate
