### ISSUE TITLE
[BUG] element tag select error

### ISSUE THREAD

**Issue by arezascarlet** [tabler/tabler#1090] opened 2022-03-22 07:51 UTC
i found  the bug when i fill the form use Tab key, select tag is blank, but if we click with cursor is normally

![image](https://user-images.githubusercontent.com/49219720/159432982-1c66726a-d0ce-4275-a110-4bdb44e0d506.png)

**Comment by handsome-me** [comment] 2022-03-23 03:43
Hello,
Can you assign this issue to me?

**Comment by arezascarlet** [comment] 2022-03-23 04:04
> Hello, Can you assign this issue to me?

sorry i don't have permission to assign

**Comment by rjd22** [comment] 2022-03-23 09:38
This is a duplicate of #1079 and a fix is waiting for release

**Closed by rjd22** 2022-03-23 09:38 UTC
Labels: bug

**Comment by handsome-me** [comment] 2022-03-23 09:58
I want to contribute to tabler so where can I start?
