### ISSUE TITLE
[BUG] The official manual code does not display

### ISSUE THREAD

**Issue by stephenyaoshun** [tabler/tabler#2010] opened 2024-12-12 10:03 UTC
### Browser

chrome

### OS

win10

### Screen size

1920*1080

### Describe the bug

All the code blocks on the official website's documentation page are blank. I tried all browsers, edge, firefox, chrome, and even the browser in a virtual machine couldn't display the code. Please fix it quickly.
![image](https://github.com/user-attachments/assets/236ad672-43a9-4b12-b700-f58481c42472)

### How to reproduce

2. Click on '...'
3. Scroll down to '...'
...

**Comment by graf0** [comment] 2024-12-12 19:28
confirm - no examples and no code in docs. I'm using firefox - but also checked on edge, same result

**Comment by ahmadfarisfs** [comment] 2024-12-13 09:43
Same here

**Comment by stephenyaoshun** [comment] 2024-12-14 04:00
2 days have passed, the problem still exists, this is how you treat your work, I doubt the reliability of your product

**Comment by rjd22** [comment] 2024-12-27 11:27
Closing because of duplicate of #2012

**Closed by rjd22** 2024-12-27 11:27 UTC
Labels: bug
