### ISSUE TITLE
Issue with Tabler Data tables 

### ISSUE THREAD

**Issue by pravy83** [tabler/tabler#1201] opened 2022-08-12 04:08 UTC
Dear All - greetings,

I was going through the Live Demo of Tabler bootstrap template. 
**https://preview.tabler.io/tables.html**

Realized that there are 3 issues with the Data Tables in the demo.

1) Search in data tables is not working. 
2) Pagination of the data tables is not working. 
3) Select all records feature is not working (Selecting all records by clicking on the checkbox of the 1st Column)

Tried searching in documentation however not got any idea. 

Can any one help me here. 

Regards,
Pravy

**Comment by aperezApartments247** [comment] 2022-08-12 14:21
Noticed this issue as well Pravy. From diving a little deeper, it looks like they went the bootstrap method where they provide the aesthetics, but its up to the developer to add logic to the table component. 

Having said that, I did notice that they added a new "datatable" component that seems to have a sort feature working. However, this component is not in the docs. Id be interested if anyone knows if this will be added to the docs soon, also will this component eventually include pagination, search, and other filters? 

In the mean time, Pravy take a look at [https://datatables.net/], I gave it a test with the Table component markup and classes from Tabler and they seem to work perfectly together!

**Comment by Lickity** [comment] 2022-08-16 04:07
The Datatables example is using https://listjs.com/ for sorting.

**Comment by arnauos** [comment] 2022-08-16 17:04
> In the mean time, Pravy take a look at [Datatables](https://datatables.net/), I gave it a test with the Table component markup and classes from Tabler and they seem to work perfectly together!

Any more details on how you did use the markup and classes? Adding both DTT js and css (bs5 version) makes everything work but elements like the search box, buttons and pagination look a bit out of place (mostly wrong spacing or alignment).

**Comment by sensahin** [comment] 2022-08-19 05:06
This works fine;

```
<div class="card">
  <div class="card-body">
    <div class="table-responsive">
      <table id="example" class="display" style="width:100%">
        <thead>
          <tr>
            <th>#</th>
            <th>Header</th>
            <th>Header</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>#</th>
            <th>Footer</th>
            <th>Footer</th>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>
```

**Comment by rjd22** [comment] 2022-08-31 09:02
The tables on the https://preview.tabler.io/tables.html page are not real data table implementations but style samples for you to add logic to yourself. For the data table implementation check this page: https://preview.tabler.io/datatables.html

Closing this because it's not a bug.

**Closed by rjd22** 2022-08-31 09:02 UTC
