### ISSUE TITLE
[BUG] Dropdown menu inside table shows scroll bar

### ISSUE THREAD

**Issue by herchila** [tabler/tabler#650] opened 2020-06-26 14:56 UTC
**Describe the bug**

Scroll bar appears randomly when I clicked the dropdown menu:

<img width="550" alt="Screen Shot 2020-06-26 at 11 38 32 AM" src="https://user-images.githubusercontent.com/729767/85870424-5dd4c980-b7a3-11ea-8c19-46c125b42fd2.png">

It fails in Chrome and Safari. It works in Firefox.

**Device**

 - Browser: Chrome Version 83 | Safari Version 13.1.1
 - OS: macOS 10.15
 - Screen size [e.g. 800x600]

**To reproduce**

1. Go to table with action dropdown button
2. Click on 3-dots options
3. See error

**Comment by FreexD** [comment] 2020-11-25 20:29
Duplicate of #698

**Closed by FreexD** 2020-11-25 20:29 UTC
Labels: bug
