### ISSUE TITLE
[BUG] - action button text on table overflow in dropdown

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1539] opened 2023-04-21 05:52 UTC
![image](https://user-images.githubusercontent.com/6236128/233551242-4900ceda-09bb-4e47-acd1-608489959efe.png)

here example 

happend if you have on th class w-1  sometimes even without it 

```
 <span class="dropdown">
                                              <button class="btn dropdown-toggle align-text-top"
                                                      data-bs-boundary="viewport" data-bs-toggle="dropdown"
                                                      aria-expanded="false">Actions</button>
                                              <div class="dropdown-menu dropdown-menu-end" style="">
                                                <a class="dropdown-item" href="#">
                                                  Mark as bot
                                                </a>
                                                <a class="dropdown-item" href="#">
                                                  Block this IP/user
                                                </a>
                                              </div>
                                            </span>
```

An Update:

this somehow fix the issue:

```
 <div class="btn-list flex-nowrap">
                                              <a href="{{ route('admin.advanced-search.edit', 1) }}" class="btn">
                                                  Edit
                                              </a>
                                              <div class="dropdown">
                                                  <button class="btn dropdown-toggle align-text-top" data-bs-toggle="dropdown">
                                                      Actions
                                                  </button>
                                                  <div class="dropdown-menu dropdown-menu-end">
                                                      <a class="dropdown-item" href="#">
                                                          Mark as bot
                                                      </a>
                                                      <a class="dropdown-item" href="#">
                                                          Block this IP/user
                                                      </a>
                                                  </div>
                                              </div>
                                          </div>
```

**Comment by rjd22** [comment] 2023-04-22 10:24
This is a duplicate of: https://github.com/tabler/tabler/issues/1400

Sadly there is no way to fix this afaik without breaking other functionality so closing this.

**Closed by rjd22** 2023-04-22 10:24 UTC
Labels: bug
